In [1]:
# NumPy Arrays

# Creating arrays with NumPy

import numpy as np



In [2]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
# Converting a normal list to an numpy array.

np.array(mylist)

array([1, 2, 3])

In [4]:
mylist

[1, 2, 3]

In [6]:
my_arr = np.array(mylist)

In [7]:
type(my_arr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3], [1,2,3], [1,2,3]]

In [9]:
my_matrix

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [13]:
# Creating an numpy array with a single command

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
# Creating 5x5 zeros matrix    (rows, columns)

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# This is a similar creating method, the difference is: Syntax np.linspace(lower limit, upper limit, # of numbers we want between limits)

np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
# Identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Random generator:

np.random.rand(1)

array([0.6405747])

In [24]:
np.random.rand(5,5)

array([[0.03822816, 0.19667125, 0.83173106, 0.19937298, 0.85671964],
       [0.05041143, 0.13131007, 0.22429994, 0.14892467, 0.87203763],
       [0.97928085, 0.23241672, 0.94851868, 0.9090296 , 0.48335089],
       [0.88635629, 0.91033923, 0.68884271, 0.6511433 , 0.22184052],
       [0.58457432, 0.98971212, 0.61419625, 0.15048069, 0.62720792]])

In [25]:
# Standart Normal Distribution

np.random.randn(7)

array([-2.21263029, -0.03613164, -1.35778129, -0.25553064,  1.167661  ,
       -1.26767787, -1.24177369])

In [26]:
np.random.randn(2,2)

array([[-0.06634117,  0.6621226 ],
       [ 0.82227488,  0.38327254]])

In [33]:
# Random integers
# Syntax: np.random.randint(lower limit, upper limit, #number of randoms we want or (n,m) <--- Matrix)

np.random.randint(0,101,5)

array([ 3, 78, 83, 85, 57])

In [34]:
np.random.randint(0,101,(3,3))

array([[60, 74,  7],
       [76,  9, 72],
       [68, 28, 55]])

In [41]:
# We can plant a seed to make our random numbers reproducible.

np.random.seed(42) # <------------- the argument is an arbitrary number

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [42]:
np.random.seed(42) # <-------------

np.random.rand(4)

# It works c:

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
# Attributes 

arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
new_arr = arr.reshape(5,5)
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
rand_array = np.random.randint(0,101,10)
rand_array

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [50]:
rand_array.min()

2

In [51]:
rand_array.max()

99

In [52]:
rand_array.argmax()

5

In [53]:
rand_array.dtype

dtype('int32')

In [1]:
new_arr.shape

NameError: name 'new_arr' is not defined

In [5]:
# Is not recommended anymore to use a seed for reproducible random numbers, instead:

import numpy as np

rng = np.random.default_rng(2021)
rng.random(4)

array([0.75694783, 0.94138187, 0.59246304, 0.31884171])

In [4]:
# This are not the same ressults for the seed method, but if we want them we can replicate them using RandomState

rng2 = np.random.RandomState(2021)
rng2.random(4)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308])