In [1]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[8]

8

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [4]:
arr [:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# To modify certain values on a range we can:

arr [0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Doing the following will not make a copy of certain part of the original array, is just making a subarray. So if we modify the subarray, this will also modify the original array.

slice_of_arr = arr[0:5]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:
# If we change the value of this subarray

slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
# This will affect the original array

arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
# If we don't want to modify the original array, we need to COPY the part of the array to another one.

arr_copy = arr.copy()

In [22]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
# Indexing on 2D arrays

arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [28]:
arr_2d[1]

array([20, 25, 30])

In [29]:
arr_2d[1][1]

25

In [30]:
arr_2d[1,1]

25

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
# Conditional Selection

array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_array = array > 4

In [38]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
# Returning index locations of the objects that satisfy the condition array > 4
array[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
# ONE LINE METHOD

array[array > 4]

array([ 5,  6,  7,  8,  9, 10])