In [1]:
# NUMPY OPERATIONS

import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr / 0

C:\Users\carmg\AppData\Local\Temp/ipykernel_16880/3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
C:\Users\carmg\AppData\Local\Temp/ipykernel_16880/3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [5]:
1/0

ZeroDivisionError: division by zero

In [6]:
1/ arr

C:\Users\carmg\AppData\Local\Temp/ipykernel_16880/3009366600.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [9]:
np.log(arr)

C:\Users\carmg\AppData\Local\Temp/ipykernel_16880/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.sum()

45

In [12]:
arr.mean()

4.5

In [13]:
arr.max()

9

In [14]:
arr.var()

8.25

In [15]:
arr.std()

2.8722813232690143

In [16]:
array_2d = np.arange(0,25).reshape(5,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
array_2d.sum()

300

In [19]:
# Specifying axis parameter
# axis = 0: sum opperating for each column
array_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [20]:
# axis = 1: sum operation for each row

array_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])